// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteServer(arg1:number):Promise<void>;

export function GetStatus():Promise<main.StatusResponse>;

export function Quit():Promise<void>;

export function SaveConfig(arg1:number,arg2:number):Promise<void>;

export function SaveServer(arg1:main.ServerInput):Promise<void>;

export function SwitchServer(arg1:number):Promise<void>;

export function ToggleProxy():Promise<main.ToggleResponse>;
