// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SaveConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2);
}

export function SaveServer(arg1) {
  return window['go']['main']['App']['SaveServer'](arg1);
}

export function SwitchServer(arg1) {
  return window['go']['main']['App']['SwitchServer'](arg1);
}

export function ToggleProxy() {
  return window['go']['main']['App']['ToggleProxy']();
}
